[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --omit=dev --no-audit --no-fund"]

[phases.build]
cmds = ["echo 'Static site ready'"]

[start]
cmd = "cd web-project && npm start"
