[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd backend-api && npm ci --only=production']

[phases.build]
cmds = ['echo "Backend API ready for deployment"']

[start]
cmd = 'cd backend-api && node server.js'
