# SmartFarm Railway Configuration
[service]
name = "smartfarm-backend"
root = "backend"
start = "node server-simple.cjs"
healthcheckPath = "/api/health"
healthcheckTimeout = 120

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server-simple.cjs"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables will be set in Railway dashboard