[build]
builder = "nixpacks"
rootDirectory = "backend-api"
buildCommand = "cd backend-api && npm install --production"

[deploy]
startCommand = "cd backend-api && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
