[build]
builder = "nixpacks"
rootDirectory = "backend-api"

[deploy]
startCommand = "npm ci --only=production && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
