[build]
builder = "nixpacks"
rootDirectory = "railway-backend"

[deploy]
startCommand = "cd railway-backend && npm install && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
