[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.clean"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
API_VERSION = "1.0.0"
API_NAME = "SmartFarm API"
LOG_LEVEL = "info"
CORS_ORIGIN = "*"