package com.smartfarm.ui.screens.forms

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.smartfarm.shared.data.model.dto.FarmDto
import com.smartfarm.shared.data.model.dto.LocationDto
import com.smartfarm.ui.components.EntityFormDialog

@Composable
fun AddFarmDialog(
    onDismiss: () -> Unit,
    onSave: (FarmDto) -> Unit
) {
    var name by remember { mutableStateOf("") }
    var address by remember { mutableStateOf("") }
    var latitude by remember { mutableStateOf("") }
    var longitude by remember { mutableStateOf("") }
    var size by remember { mutableStateOf("") }
    var type by remember { mutableStateOf("MIXED") }
    var ownerId by remember { mutableStateOf("") }
    
    EntityFormDialog(
        title = "Add Farm",
        onDismiss = onDismiss,
        onSave = {
            if (name.isNotBlank() && address.isNotBlank()) {
                val farm = FarmDto(
                    id = "", // Will be generated by backend
                    name = name,
                    location = LocationDto(
                        latitude = latitude.toDoubleOrNull() ?: 0.0,
                        longitude = longitude.toDoubleOrNull() ?: 0.0,
                        address = address
                    ),
                    size = size.toDoubleOrNull() ?: 0.0,
                    type = type,
                    status = "ACTIVE",
                    ownerId = ownerId.ifBlank { "1" },
                    isActive = true
                )
                onSave(farm)
            }
        }
    ) {
        OutlinedTextField(
            value = name,
            onValueChange = { name = it },
            label = { Text("Farm Name *") },
            modifier = Modifier
                .fillMaxWidth()
                .padding(bottom = 16.dp),
            singleLine = true
        )
        
        OutlinedTextField(
            value = address,
            onValueChange = { address = it },
            label = { Text("Address *") },
            modifier = Modifier
                .fillMaxWidth()
                .padding(bottom = 16.dp),
            singleLine = true
        )
        
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            OutlinedTextField(
                value = latitude,
                onValueChange = { latitude = it },
                label = { Text("Latitude") },
                modifier = Modifier.weight(1f),
                singleLine = true
            )
            OutlinedTextField(
                value = longitude,
                onValueChange = { longitude = it },
                label = { Text("Longitude") },
                modifier = Modifier.weight(1f),
                singleLine = true
            )
        }
        
        OutlinedTextField(
            value = size,
            onValueChange = { size = it },
            label = { Text("Size (acres)") },
            modifier = Modifier
                .fillMaxWidth()
                .padding(bottom = 16.dp),
            singleLine = true
        )
        
        var expanded by remember { mutableStateOf(false) }
        ExposedDropdownMenuBox(
            expanded = expanded,
            onExpandedChange = { expanded = !expanded },
            modifier = Modifier
                .fillMaxWidth()
                .padding(bottom = 16.dp)
        ) {
            OutlinedTextField(
                value = type,
                onValueChange = {},
                readOnly = true,
                label = { Text("Farm Type") },
                trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) },
                modifier = Modifier.menuAnchor()
            )
            ExposedDropdownMenu(
                expanded = expanded,
                onDismissRequest = { expanded = false }
            ) {
                listOf("CROP", "LIVESTOCK", "MIXED", "DAIRY", "POULTRY", "AQUACULTURE").forEach { option ->
                    DropdownMenuItem(
                        text = { Text(option) },
                        onClick = {
                            type = option
                            expanded = false
                        }
                    )
                }
            }
        }
    }
}

