# SmartFarm Backend Railway Configuration
[service]
name = "smartfarm-backend"
root = "."
start = "node server-production.cjs"
healthcheckPath = "/api/health"
healthcheckTimeout = 120

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables will be set in Railway dashboard