# SmartFarm Frontend - Netlify Configuration
# Optimized for static site deployment

[build]
  # Build command for static site
  command = "npm run build"
  
  # Publish directory (where your built files are)
  publish = "public"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Development settings
[dev]
  command = "npm run dev"
  port = 8080
  publish = "public"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://api.railway.app https://smartfarm-backend.railway.app https://smartfarm-app-production.up.railway.app; frame-ancestors 'none';"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Form handling
[forms]
  # Enable form detection
  [forms.settings]

# Functions directory (if you add serverless functions later)
[functions]
  directory = "netlify/functions"

# Plugins for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.8
